package CLASESATABLAS;
// Generated Mar 7, 2016 8:24:31 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Servidor generated by hbm2java
 */
@Entity
@Table(name="servidor"
    ,schema="public"
)
public class Servidor  implements java.io.Serializable {


     private int nidusuario;
     private Usuario usuario;
     private Integer visitas;

    public Servidor() {
    }

	
    public Servidor(Usuario usuario) {
        this.usuario = usuario;
    }
    public Servidor(Usuario usuario, Integer visitas) {
       this.usuario = usuario;
       this.visitas = visitas;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="usuario"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="nidusuario", unique=true, nullable=false)
    public int getNidusuario() {
        return this.nidusuario;
    }
    
    public void setNidusuario(int nidusuario) {
        this.nidusuario = nidusuario;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="visitas")
    public Integer getVisitas() {
        return this.visitas;
    }
    
    public void setVisitas(Integer visitas) {
        this.visitas = visitas;
    }




}


